- src/spiffs_hydrogen.c
when reading beyond file size, and when spiffs_object_read return SPIFFS_OK,
the length add to offset should be "avail" instead of len.
please review.
> fix SPIFFS_read length when reading beyond file size

- src/spiffs_nucleus.h
`SPIFFS_OBJ_ID_IX_FLAG` should be the same type as spiffs_obj_id, otherwise it defaults to (signed) int and causes a warning
```
/home/benpicco/dev/volaWare/module/spiffs/spiffs_nucleus.c: In function 'spiffs_erase_block':
/home/benpicco/dev/volaWare/module/spiffs/spiffs_nucleus.c:252:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (fs->max_erase_count == SPIFFS_OBJ_ID_IX_FLAG) {
```
> fix warning when spiffs_obj_id is 32 bit

- src/spiffs_hydrogen.c
According to posix, lseek returns the resulting offset.
> lseek should return the resulting offset

- src/spiffs.h
- src/spiffs_hydrogen.c
- src/spiffs_nucleus.c
When SPIFFS_CACHE is defined as 0 there are warnings during build for unused variables and unused static functions. This patch fix those build warnings.
> Fix build warnings when SPIFFS_CACHE set to 0

- src/spiffs_gc.c
align cand_scores to prevent data aborts on architectures with alignment
restrictions
> align cand_scores

- src/spiffs_gc.c
Casting 64-bit `cand_scores` pointer to u32_t discards MSBs which causes segfault later in the code. Use ptrdiff_t type instead.
Without this change, test suite segfaults in `write_big_files_chunks_1` on 64-bit OSX 10.10.
With this change, test suite passes.
> Fix pointer truncation on 64-bit platforms

- src/spiffs_gc.c
This caused a compilation error with strictest setting on an embedded compiler
> Removed unnecessary parameter in debug printout

- src/spiffs_hydrogen.c
Otherwise there is no way to use it in callbacks invoked during mount.
pellepl/spiffs#34
> Preserve user_data during mount()

- src/spiffs.h
- src/spiffs_check.c
- src/spiffs_hydrogen.c
- src/spiffs_nucleus.c
- src/spiffs_nucleus.h
They don't get changed so might as well make them const, then users know.
Done as part of improving the integration with [Sming](http://github.com/SmingHub/Sming).
> make api string params const

- src/spiffs.h
- src/spiffs_hydrogen.c
When upgrading sming to use the latest version of spiffs I found these functions in the old code. I don't know where they originate from but we use them and they might be handy for others too.
> add tell and eof functions

- src/spiffs_hydrogen.c
The proposed change sets the file offset to the file's end when the file size is smaller than the expected seek index. This allows to use seek to put the file location to a certain position or the end.
> set file offset when seeking over end

- .travis.yml
- src/default/spiffs_config.h
- src/spiffs.h
- src/spiffs_gc.c
- src/spiffs_hydrogen.c
- src/spiffs_nucleus.c
- src/spiffs_nucleus.h
- src/test/test_bugreports.c
- src/test/test_hydrogen.c
- src/test/test_spiffs.c
Metadata is stored in the file index structure and is opaque to SPIFFS.
It allows user to associate additional information with a file.
Fixes pellepl/spiffs#127
> Add optional file metadata

- src/spiffs_nucleus.c
- src/spiffs_nucleus.h
Error[Pe094]: the size of an array must be greater than zero 
\spiffs\spiffs_nucleus.c 981
> when SPIFFS_OBJ_META_LEN = 0, it can cause some compile error.

- src/test/test_bugreports.c
- src/test/test_spiffs.c
This also fixes a big of diagnostic logging that failed to use the correct page size.
It also adds a test case around a bad interaction between GC and writing...
It also does not abort the test if the write (or read) is out of bounds -- it just fails the test.
> This makes the tests pass again (by making them non-default tests)

- src/spiffs_nucleus.c
In both lines changed:
* An integer quantity is incremented then decremented, which amounts to a no-op (and may cause the compiler to consider the whole expression as undefined behavior due to the possibility of overflow): remove both increment and decrement.
* the right side of a comparison (hidden within the `MIN` or `MAX` macro) is cast from unsigned to signed probably in order to please  the compiler when the left side is a `u16_t` (and thus may get promoted to a bigger-sized signed int on 32- or 64-bit architectures). Remove the right side cast and cast the left side to `u32_t` (which is the expected type of the `MIN` or `MAX` result) instead, which pleases the compiler whatever the size of the left side.
Note: `make test` passes all 82 tests, and `make build-all` succeeds.
> src/spiffs_nucleus: remove useless +1/-1 and force comparison to unsigned

- py/Makefile
- py/params_test.h
- py/python_ops.c
- py/sp_test.py
- py/spiffs.py
It is convenient (for my purposes) to have binding to manipulate a filesystem from Python.
Here is the binding I have developed for this purpose.
`spiffs.py`, run by itself, will attempt to compile spiffs as a shared object file and load it with `ctypes`.
The filesystem is represented as a `Spiffs()` class, with examples provided of a file-backing or list-of-chars backing.
See the `__main__` function for examples of use.
No changes were required of the C code, although I did find it helpful to write a couple of C shim functions, rather than wrap everything directly in `ctypes`.  I used stdint.h typedefs to provide the `s32_t` etc. names.
> Python binding

- src/spiffs_nucleus.h
And compilation fails without it
> TI compiler supports __attribute__((packed))

- .travis.yml
- src/default/spiffs_config.h
- src/spiffs_check.c
- src/spiffs_nucleus.c
- src/test/test_spiffs.c
Only reset those that are set, do not assume that 0 -> 1 writes are ignored.
(hopefully) fixes https://github.com/pellepl/spiffs/issues/172
> Be careful resetting flag bits

- src/spiffs_nucleus.h
cppcheck produces the following warning: Redundant assignment of 'fh' to itself.
This change implements a workaround.
> Work around for cppcheck warning.

- src/default/spiffs_config.h
- src/spiffs_nucleus.c
For some applications (like storing keys and sensitive data) secure erase is required option
> Add secure erase via zeroing page contents on deletion

- src/default/spiffs_config.h
For reasons unknown to me, somebody changed the size of some internal spiffs types from 16 to 32 bits (spiffs_block_ix, spiffs_page_ix, spiffs_obj_id, spiffs_span_ix) on our device.
As I was updating our spiffs source to the current head, I followed the model suggested by params_test.h and I pulled out all of our changes to the default spiffs_config.h into a separate file to minimize future merging headaches. Of course, I had to wrap these type changes with an `#ifndef SPIFFS_TYPES_OVERRIDE` block to make the scheme work.
> Add ability to override the sizes of spiffs internal data types

- src/spiffs_check.c
Hi there,
I was testing a file system configuration with a logical page size of 32 KiB and got the following compiler warning:
```
In file included from spiffs/src/spiffs.h:14:0,
from spiffs/src/spiffs_check.c:23:
spiffs/src/spiffs_check.c: In function 'spiffs_page_consistency_check_i':
../shared/spiffs_config.h:223:43: warning: large integer implicitly truncated to unsigned type [-Woverflow]
#define SPIFFS_CFG_LOG_PAGE_SZ(ignore)    (32 * 1024)
^
spiffs/src/spiffs_check.c:524:41: note: in expansion of macro 'SPIFFS_CFG_LOG_PAGE_SZ'
const spiffs_page_ix pages_per_scan = SPIFFS_CFG_LOG_PAGE_SZ(fs) * 8 / bits;
```
My file system is 124 MiB in size, so I chose uint16_t as the type used to store `spiffs_page_ix`, because a `uint16_t` can safely store page indices for the roughly 4,000 pages …
> Fix possible source of overflow in SPIFFS_check

- src/spiffs_hydrogen.c
- src/spiffs_nucleus.c
In our projects we have strict set of gcc warnings and we also build Release configuration, thus we had to introduce these commits to make our build pipeline happy.
> Fix gcc release warnings

- src/spiffs_nucleus.c
This fix handles the gcc's `-Wstringop-truncation` warning.
See:
<https://stackoverflow.com/questions/50198319/gcc-8-wstringop-truncation-what-is-the-good-practice>
> Fix strncpy truncating NUL terminating char

- src/spiffs_hydrogen.c
- src/test/test_hydrogen.c
When iteration finishes, `spiffs_obj_lu_find_entry_visitor` returns
`SPIFFS_VIS_END`. Previously, `SPIFFS_readdir` function used to set
`errno` to this internal error value when readdir reached the end.
Handle this case and add a check into the regression test.
(Original issue: https://github.com/esp-rs/rust/issues/117#issuecomment-1142159661)
> fix SPIFFS_readdir setting errno to SPIFFS_VIS_END at the end of iteration
